name: Create WebSocket Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - run: |
        sudo wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        sudo cloudflared service install ${{ secrets.CF_ID }}
        sudo systemctl start cloudflared

    - name: Install dependencies
      run: npm install ws express formidable --save

    # - uses: gautamkrishnar/keepalive-workflow@v2
    #   with:
    #     gh_token: ${{ secrets.TOKEN_GITHUB }}
    #     committer_username: RapiIlham
    #     committer_email: t.eratmbl1@gmail.com

    - name: Commit and Push Changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: RapiIlham
        author_email: t.eratmbl1@gmail.com
        message: "Auto commit: Updated last_commit.txt"
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          
    - name: Create WebSocket server
      run: node hello.js
