name: Create WebSocket Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - run: |
        sudo wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        sudo cloudflared service install ${{ secrets.CF_ID }}
        sudo systemctl start cloudflared

    - name: Install dependencies
      run: npm install ws

    - name: Create WebSocket server
      run: node hello.mjs
