name: Create WebSocket Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    timeout-minutes: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - run: |
        sudo wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        sudo cloudflared service install ${{ secrets.CF_ID }}
        sudo systemctl start cloudflared

    - name: Install dependencies
      run: npm install ws express formidable --save

    - name: Create WebSocket server
      run: node hello.js

    - uses: gautamkrishnar/keepalive-workflow@v2
      continue-on-error: true
