name: Create WebSocket Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - run: |
        sudo wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        sudo cloudflared service install ${{ secrets.CF_ID }}
        sudo systemctl start cloudflared

    - name: Install dependencies
      run: npm install ws express formidable --save

    # - uses: gautamkrishnar/keepalive-workflow@v2
    #   with:
    #     gh_token: ${{ secrets.TOKEN_GITHUB }}
    #     committer_username: RapiIlham
    #     committer_email: t.eratmbl1@gmail.com

    - name: Git config
      run: |
        git config --global user.email "t.eratmbl1@gmail.com"
        git config --global user.name "RapiIlham"

    - name: Commit and push
      run: |
        git commit -am "Keep repository active"
        git push origin main

    - name: Create WebSocket server
      run: node hello.js
